// <auto-generated />
using Gestao_Composicoes_Autorais_Src.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gestao_Composicoes_Autorais_Src.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210917212000_Mysql_Update")]
    partial class Mysql_Update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("AutorMusica", b =>
                {
                    b.Property<long>("AutoresId")
                        .HasColumnType("bigint");

                    b.Property<long>("MusicasId")
                        .HasColumnType("bigint");

                    b.HasKey("AutoresId", "MusicasId");

                    b.HasIndex("MusicasId");

                    b.ToTable("AutorMusica");
                });

            modelBuilder.Entity("Gestao_Composicoes_Autorais_Src.Model.Autor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("Gestao_Composicoes_Autorais_Src.Model.Musica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Musicas");
                });

            modelBuilder.Entity("AutorMusica", b =>
                {
                    b.HasOne("Gestao_Composicoes_Autorais_Src.Model.Autor", null)
                        .WithMany()
                        .HasForeignKey("AutoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestao_Composicoes_Autorais_Src.Model.Musica", null)
                        .WithMany()
                        .HasForeignKey("MusicasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
