name: Bulild and Test API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore /home/runner/work/Gestao-Composicoes-Autorais/Gestao-Composicoes-Autorais/Gestao-Composicoes-Autorais-Api/Gestao-Composicoes-Autorais-Api.sln
    - name: Build
      run: dotnet build --no-restore /home/runner/work/Gestao-Composicoes-Autorais/Gestao-Composicoes-Autorais/Gestao-Composicoes-Autorais-Api/Gestao-Composicoes-Autorais-Api.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal /home/runner/work/Gestao-Composicoes-Autorais/Gestao-Composicoes-Autorais/Gestao-Composicoes-Autorais-Api/Gestao-Composicoes-Autorais-Api.sln
